const pageTitle = document.querySelector("title");
const photoBack = document.querySelector("#photoBack");
const photoFront = document.querySelector("#photoFront");
const messageAuthor = document.querySelector(".card__message__author");
const message = document.querySelector(".card__message__txt");
const audio = document.querySelector("#audio");

const buildMessagePage = () => {
    let currentPageUrl = window.location.href;
    let searchUrl = new URLSearchParams(currentPageUrl);
    for (let p of searchUrl) {
        let currentPageId = p[1];
        console.log(currentPageId);
        switch(currentPageId) {
            case "guillaume":
                console.log("Message de Guillaume");
                pageTitle.innerHTML = "Guillaume";
                photoBack.setAttribute("src", "../img/guillaume2.jpeg");
                photoBack.setAttribute("alt", "Guillaume et Marussia à Rimouski");
                photoFront.setAttribute("src", "../img/guillaume.jpg");
                photoFront.setAttribute("alt", "Guillaume et Marussia sur la plage en Gaspésie");
                messageAuthor.innerHTML = "Guillaume";
                message.innerHTML = "C'est la cinquième fois que je te souhaite ton anniversaire aujourd'hui, et je suis toujours aussi excité, comme la première fois.<br /> Voilà mon petit cadeau fait-maison traditionnel: une déclaration d'amour collaborative! Pour que tu continues de rayonner dans ma vie et dans celles de tous tes amis et de ta famille.<br /> Je t'aime.<br /> Joyeux anniversaire <i class='fas fa-heart'></i>";
                audio.setAttribute("src", "../mus/guillaume.mp3");
                break;
            case "juliette":
                console.log("Message de Juliette");
                pageTitle.innerHTML = "Juliette";
                photoBack.setAttribute("src", "../img/juliette2.png");
                photoBack.setAttribute("alt", "Juliette et Marussia jouent une pièce de théâtre");
                photoFront.setAttribute("src", "../img/juliette.png");
                photoFront.setAttribute("alt", "Juliette et Marussia petites");
                messageAuthor.innerHTML = "Juliette";
                message.innerHTML = "Joyeux anniversaire ma grande soeur chérie d’amour ! <br /> J’ai choisi ces deux photos car elles montrent à la perfection la philosophie qui nous anime: se supporter dans les bons, comme dans les mauvais moments. <br /> Je t’aime fort !";
                audio.setAttribute("src", "../mus/juliette.mp3");
                break;
            case "alix":
                console.log("Message d'Alix");
                pageTitle.innerHTML = "Alix";
                photoBack.setAttribute("src", "../img/alix2.jpg");
                photoBack.setAttribute("alt", "Alix, Marussia et d'autres amis en soirée");
                photoFront.setAttribute("src", "../img/alix.jpg");
                photoFront.setAttribute("alt", "Alix et Marussia aux 24 ans de Marussia");
                messageAuthor.innerHTML = "Alix";
                message.innerHTML = "Ma Maru d’amour, belle de nuit comme de jour,<br /> Je te souhaite un magnifique anniversaire et une magnifique journée bien entourée,<br /> Et puis en fait je te souhaite tout le bonheur du monde, je t’aime très très très très très fort,<br /> Parce que comme dit Angèle, Que Du Love.<br /> PS: J'ai extrêmement hâte de te retrouver.";
                audio.setAttribute("src", "../mus/alix.mp3");
                break;
            case "darons":
                console.log("Message de Catherine et Thierry");
                pageTitle.innerHTML = "Catherine et Thierry";
                photoBack.setAttribute("src", "../img/darons2.jpg");
                photoBack.setAttribute("alt", "Marussia, Guillaume et ses parents prennent l'apéro sur la plage en Martinique");
                photoFront.setAttribute("src", "../img/darons.jpg");
                photoFront.setAttribute("alt", "Les parents de Guillaume en Martinique");
                messageAuthor.innerHTML = "Catherine et Thierry";
                messageAuthor.classList.add("card__message__author--long");
                message.innerHTML = "Tu es un rayon de soleil.<br /> Ne change surtout pas!<br /> Joyeux anniversaire,<br /> avec toute notre affection <i class='fas fa-heart'></i>";
                audio.setAttribute("src", "../mus/darons.mp3");
                break;   
            case "morgane":
                console.log("Message de Morgane");
                pageTitle.innerHTML = "Morgane";
                photoBack.setAttribute("src", "../img/morgane2.jpg");
                photoBack.setAttribute("alt", "Marussia à Montréal, de dos avec son bonnet ours");
                photoFront.setAttribute("src", "../img/morgane.jpg");
                photoFront.setAttribute("alt", "Morgane et son chat");
                messageAuthor.innerHTML = "Morgane";
                message.classList.add("card__message__txt--less-margin");
                message.classList.add("card__message__txt--sm");
                message.innerHTML = "Coucou ma poulette,<br />Je suis heureuse de te voir évoluer dans ce que tu aimes... Prends soin de toi car nous en avons besoin pour apporter tout l’amour autour de nous... Sois à l’écoute mais pas trop, ambitieuse et consciente de la chance que tu peux déjà avoir... Je te souhaite le meilleur et bien plus encore ! Contente de recréer quelque chose avec toi...<br />Excellent anniversaire ma belle Marussia 🎂<br />Kiss kiss love love<br />*Ta Ta MoOommo qu’est-ce qu’elle a sous son gros boOnnNet 🙂";
                audio.setAttribute("src", "../mus/morgane.mp3");
                break;   
            case "bib":
                console.log("Message de Briac");
                pageTitle.innerHTML = "Briac";
                photoBack.setAttribute("src", "../img/bib2.jpg");
                photoBack.setAttribute("alt", "Briac fait semblant de sniffer de la cocaïne");
                photoFront.setAttribute("src", "../img/bib.jpg");
                photoFront.setAttribute("alt", "Selfie de Briac");
                messageAuthor.innerHTML = "Briac";
                message.classList.add("card__message__txt--less-margin");
                message.innerHTML = "Joyeux anniversaire Marussia!<br /> En prenant un peu de recul je réalise que l'on s'est rencontré il y a 4 ans déjà et pourtant on ne se connait pas si bien que ça. Cela n'empêche que tu m'as déjà apporté pas mal de positif dans ma vie, rien qu'en rendant mon cousin heureux ce qui n'était pas forcement gagné d'avance puis en me faisant découvrir Montréal aussi mais surtout, en me transmettant ton savoir en matière de magie noire!  J'ai hâte d'être enfin à Nantes l'année prochaine pour que l'on puisse se voir plus!";
                audio.setAttribute("src", "../mus/bib.mp3");
                break;
            case "lucie":
                console.log("Message de Lucie");
                pageTitle.innerHTML = "Lucie";
                photoBack.setAttribute("src", "../img/lucie3.jpg");
                photoBack.setAttribute("alt", "Marussia porte Lucie chiot au parc La Fontaine");
                photoFront.classList.add("img--fill");
                photoFront.setAttribute("src", "../img/lucie.jpeg");
                photoFront.setAttribute("alt", "Lucie fait du kayak en Gaspésie");
                messageAuthor.innerHTML = "Lucie";
                message.innerHTML = "*WOUF*<br /> Je suis une saucisse qui aime sa maman même si j'aboie sur tout le monde, je me casse le dos et je mange des poubelles!";
                audio.setAttribute("src", "../mus/lucie.mp3");
                break;
            case "lalou":
                console.log("Message de Lalou et Vicky");
                pageTitle.innerHTML = "Lalou et Vicky";
                photoBack.classList.add("img--fill");
                photoBack.setAttribute("src", "../img/lalou3.jpg");
                photoBack.setAttribute("alt", "Lalou et Vicky déguisés en Frida Kahlo");
                photoFront.setAttribute("src", "../img/lalou.jpg");
                photoFront.setAttribute("alt", "Lalou et Vicky déguisés sur un balcon à Montréal");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Lalou et Vicky";
                message.classList.add("card__message__txt--less-margin");
                message.innerHTML = "Wesh Maru !<br /> Bon bah of course que tu nous manques beaucoup beaucoup ! Moi (Lalou) je m’ennuie beaucoup de tes performances épiques (d’où le choix musical tu catch ?) ! Hâte de te retrouver cet été et de faire une grosse fête de non-anniversaire commun ! Aussi, ton anniversaire marquera à jamais la dernière fête du monde d’avant, ça fait une raison de plus pour se mettre à l’envers !<br /> Muchos besos et du gros love, on t’aime fort ❤️🔥";
                audio.setAttribute("src", "../mus/lalou.mp3");
                break;
            case "hugues":
                console.log("Message de Hugues");
                pageTitle.innerHTML = "Hugues";
                photoBack.setAttribute("src", "../img/hugues2.jpg");
                photoBack.setAttribute("alt", "Hugues boit du vin dans un pichet de festival en plastique");
                photoFront.setAttribute("src", "../img/hugues.jpg");
                photoFront.setAttribute("alt", "Hugues prend la pose en extérieur");
                messageAuthor.innerHTML = "Hugues";
                message.innerHTML = "Bon anniversaire Marussia!<br />J'espère que le nom de l'interprète te plaira :D<br /><br />Indice: le nom de l'interprète c'est DANZIG.";
                audio.setAttribute("src", "../mus/hugues.mp3");
                break;
            case "naomi":
                console.log("Message de Naomi et Steve");
                pageTitle.innerHTML = "Naomi et Steve";
                photoBack.setAttribute("src", "../img/naomi2.jpg");
                photoBack.setAttribute("alt", "Naomi et Steve en patins");
                photoFront.setAttribute("src", "../img/naomi.jpg");
                photoFront.setAttribute("alt", "Naomi et Steve en vacances");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Naomi et Steve";
                message.classList.add("card__message__txt--less-margin");
                message.innerHTML = "On te souhaite un très bel anniversaire!<br /> On est heureux de connaître une fille rayonnante comme toi.<br /> La musique qu’on a choisie correspond à une story que tu avais mise quand on s’est rencontré la première fois en faisant nos roulettes <i class='fas fa-grin-alt'></i><br /> On a hâte d’avoir de nouveaux souvenirs avec toi.<br /> Ps: notre deuxième souvenir avec toi c’est ton mime de radar! F A M O U S<br /> Gros zoubiiiiii";
                audio.setAttribute("src", "../mus/naomi.mp3");
                break;
            case "anais":
                console.log("Message de Anaïs et Pierre");
                pageTitle.innerHTML = "Anaïs et Pierre";
                photoBack.setAttribute("src", "../img/anais2.jpg");
                photoBack.setAttribute("alt", "Anaïs et Pierre avec un chat");
                photoFront.setAttribute("src", "../img/anais.jpg");
                photoFront.setAttribute("alt", "Anaïs et Pierre en combinaison à la plage");
                messageAuthor.innerHTML = "Anaïs et Pierre";
                message.classList.add("card__message__txt--less-margin");
                message.classList.add("card__message__txt--xs");
                message.innerHTML = "Marussia,<br /> Tu as débarqué dans notre vie, attirée par la Suze Tonic, au vernissage d’un artiste éminent de la scène locale. Forte de ton charisme et de ta joie de vivre, tu as convaincu l’assemblée du gratin nantais, belle perf! Première étape franchie avec succès, la seconde étape permettra au jury de confirmer ton entrée au NAONED SELECT CLUB. Tu en bonne voie mais des points restent à préciser :<br /> Une bonne humeur constante,<br /> Un crazy leg maîtrisé,<br /> Un style imparable.<br /><br /> Au plaisir,<br /> Continuez ainsi!";
                audio.setAttribute("src", "../mus/anais.mp3");
                break;  
            case "william":
                console.log("Message de William, Nanou et Anna");
                pageTitle.innerHTML = "Papa, Nanou et Anna";
                photoBack.setAttribute("src", "../img/william2.jpg");
                photoBack.setAttribute("alt", "Marussia avec une couronne de roses");
                photoFront.setAttribute("src", "../img/william.jpg");
                photoFront.setAttribute("alt", "Selfie de William, Nanou et Anna");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Papa, Nanou et Anna";
                message.classList.add("card__message__txt--less-margin");
                message.innerHTML = "N’est-elle pas belle notre Marussia ? Ses jolis yeux verts, son petit sourire en coin ?<br />N’est-elle pas belle lorsqu’elle rit aux éclats ou lorsqu’elle se concentre sur son travail ?<br />N’est-elle pas belle lorsqu’elle s’interroge sur le sens de chaque chose, sur son devenir, du haut de ses 26 ans ?<br />Regardez son joli petit cœur, grand comme le monde, attentif à chacun.<br />Prenons soin d’elle !<br />Gros bisous et Joyeux anniversaire Marussia !";
                audio.setAttribute("src", "../mus/william.mp3");
                break; 
            case "winnoc":
                console.log("Message de Winnoc");
                pageTitle.innerHTML = "Winnoc";
                photoBack.classList.add("img--fill");
                photoBack.setAttribute("src", "../img/winnoc2.jpg");
                photoBack.setAttribute("alt", "Winnoc urine sur une haie");
                photoFront.setAttribute("src", "../img/winnoc.jpg");
                photoFront.setAttribute("alt", "Winnoc est chauve et beau-gosse");
                messageAuthor.innerHTML = "Winnoc";
                message.innerHTML = "Écoutez, moi je suis pas contre Marussia. Je trouve qu'elle pimente la vie. L'inconnu, c'est ce qui fascine le plus. L'Homme a besoin de points d'interrogation, ne serait-ce que pour s'en faire des porte-manteaux.<br />Biz";
                audio.setAttribute("src", "../mus/winnoc.mp3");
                break; 
            case "morve":
                console.log("Message de Morve");
                pageTitle.innerHTML = "Morwenna";
                photoBack.setAttribute("src", "../img/morve2.jpg");
                photoBack.setAttribute("alt", "Le beau front de Morwenna en gros plan");
                photoFront.setAttribute("src", "../img/morve.jpg");
                photoFront.setAttribute("alt", "Morve dans son appartement");
                messageAuthor.innerHTML = "Morve";
                message.classList.add("card__message__txt--less-margin");
                message.innerHTML = "Joyeux anniversaire!!<br />C'est une année qui sera sous le signe du renouveau, de la force et de l'épanouissement c'est certain! Je te souhaite d'être heureuse et de découvrir comment profiter de chaque instant sans penser au lendemain, tu mérites de vivre une vie épanouie!<br />Allez on se retrouve sur nos patins pour rider l'asphalte telle Lilith sortant des flammes de l'enfer. 🌞🌜";
                audio.setAttribute("src", "../mus/morve.mp3");
                break;
            case "anne":
                console.log("Message de Anne et Léo");
                pageTitle.innerHTML = "Anne et Léo";
                photoBack.classList.add("img--fill");
                photoBack.setAttribute("src", "../img/anne2.jpeg");
                photoBack.setAttribute("alt", "Anne et Léo avec un air sérieux");
                photoFront.classList.add("img--fill");
                photoFront.setAttribute("src", "../img/anne.jpeg");
                photoFront.setAttribute("alt", "Anne et Léo sont de sacrés déconneurs");
                messageAuthor.innerHTML = "Anne et Léo";
                message.classList.add("card__message__txt--sm");
                message.innerHTML = "Sept mois de séparation ont passé.<br />Il en faudra plus pour tuer notre amitié !<br />Un célèbre proverbe a dit « Loin des yeux près du cœur »,<br />Tu verras qu’on en sortira vainqueur !<br /><br />Maru, nous te souhaitons un très bel anniversaire !<br />Certes, à notre manière…<br />Vivement que l’on se serre à nouveau dans les bras,<br />Au gré de la musique (et des apéros) on festoiera !";
                audio.setAttribute("src", "../mus/anne.mp3");
                break;
            case "sandrine":
                console.log("Message de Sandrine et Mathieu");
                pageTitle.innerHTML = "Sandrine et Mathieu";
                photoBack.setAttribute("src", "../img/sandrine2.jpg");
                photoBack.setAttribute("alt", "Sandrine et Mathieu en riders");
                photoFront.setAttribute("src", "../img/sandrine.jpg");
                photoFront.setAttribute("alt", "Sandrine et Mathieu en amoureux");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Sandrine et Mathieu";
                message.innerHTML = "HAPPY B-DAYYYY MARU !!<br />Ma belle rencontre de 2020, une meuf bourrée de talent et qui mérite d'être connue (et REconnue ;) !) T'es la rideuse la plus coolos de l'Ouest, la relève de Tony Hawk est assurée ! Keep going ma biche, on t'embrasse fort et on te fait confiance pour fêter ça comme il se doit <i class='fas fa-kiss-wink-heart'></i><br /><br />Sandrine et Mathieu (les bébous) <i class='fas fa-heart'></i>";
                audio.setAttribute("src", "../mus/sandrine.mp3");
                break;
            case "mailys":
                console.log("Message de Maïlys");
                pageTitle.innerHTML = "Maïlys";
                photoBack.setAttribute("src", "../img/mailys2.jpg");
                photoBack.setAttribute("alt", "Maïlys et Max déguisés");
                photoFront.setAttribute("src", "../img/mailys.jpg");
                photoFront.setAttribute("alt", "Selfie de Maïlys");
                messageAuthor.innerHTML = "Maïlys";
                message.classList.add("card__message__txt--less-margin");
                message.classList.add("card__message__txt--xs");
                message.innerHTML = "Chère Marussia,<br />Tu es quelqu’un d’extra. Merci d’être toi. <em>(ça rime)</em><br />N’oublie pas de continuer d’être la formidable personne que tu es, sans pareille ni égale. <em>(ça rime pas mais fallait quand même le dire)</em><br />On le sait, mais le redire fait toujours plaisir : je suis vraiment heureuse de te compter parmi mes amies. La distance et les années n’ont rien changé à la relation que nous entretenons. Et ça, ça n’a pas de prix. J’espère que l’on continuera encore longtemps à se forger de beaux souvenirs ensemble !<br />Je te souhaite un merveilleux anniversaire et une nouvelle année de ta vie pleine joie et de bonheur. Et de fêtes aussi. Je pense très fort à toi pour ce jour !<br />Happy birthday Maru, bisous de Max et moi 🌞💃🏼";
                audio.setAttribute("src", "../mus/mailys.mp3");
                break;
            case "kevin":
                console.log("Message de Kévin et Romane");
                pageTitle.innerHTML = "Kévin et Romane";
                photoBack.setAttribute("src", "../img/kevin2.jpeg");
                photoBack.setAttribute("alt", "Kévin et Romane mangent une religieuse");
                photoFront.setAttribute("src", "../img/kevin.jpeg");
                photoFront.setAttribute("alt", "Kévin et Romane mangent un éclair");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Kévin et Romane";
                message.innerHTML = "Après l’éclair, vivement la religieuse de la boulangerie blanche !<br /><br />Joyeux anniversaire Marussia ! À toi et tes lasagnes végés.<br /><br />Bisous 😘";
                audio.setAttribute("src", "../mus/kevin.mp3");
                break;
            case "arseny":
                console.log("Message de Arseny et Maddison");
                pageTitle.innerHTML = "Arseny et Maddison";
                photoBack.setAttribute("src", "../img/arseny2.jpg");
                photoBack.setAttribute("alt", "Maddison et son chat");
                photoFront.setAttribute("src", "../img/arseny.jpg");
                photoFront.setAttribute("alt", "Arseny et son chat");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Arseny et Maddison";
                message.innerHTML = "Toi mon soleil de grâce en qui s'évanouit<br />La visible senteur des louanges humaines";
                audio.setAttribute("src", "../mus/arseny.mp3");
                break;
            case "charlotte":
                console.log("Message de Charlotte");
                pageTitle.innerHTML = "Charlotte";
                photoBack.setAttribute("src", "../img/charlotte2.jpg");
                photoBack.setAttribute("alt", "Charlotte et Marussia dans un élevage de poulets");
                photoFront.setAttribute("src", "../img/charlotte.jpg");
                photoFront.setAttribute("alt", "Charlotte et Marussia à Ogunquit");
                messageAuthor.innerHTML = "Charlotte";
                message.innerHTML = "Bon anniv Maru!!<br />Je m’ennuie trop de toi, j’espère que tout va bien de ton côté! Promis juré, je viens te visiter quand cette merde sera finie, ou toi viens ici hihi 😉 Je nous imagine encore en train de danser comme des folles au concert d’Aya Nakamura (ok, même s’il a été annulé) d’où mon superbe choix de musique 🔥<br />Bisous et profite bien xx";
                audio.setAttribute("src", "../mus/charlotte.mp3");
                break;
            case "tim":
                console.log("Message de Tim et Renato");
                pageTitle.innerHTML = "Tim et Renato";
                photoBack.classList.add("img--fill");
                photoBack.setAttribute("src", "../img/tim2.jpg");
                photoBack.setAttribute("alt", "Tim et Renato flous");
                photoFront.setAttribute("src", "../img/tim.jpg");
                photoFront.setAttribute("alt", "Tim et Renato avec un filtre couronne");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Tim et Renato";
                message.classList.add("card__message__txt--xs");
                message.innerHTML = "Joyeux anniversaire Marussssssiaaaaaaaaaa!<br />First thing first, you need a shot right now to celebrate. I need pictures for proof.<br />J'espère que la chanson qui joue te rappelle notre magnifique soirée débauche au Maïs because I have a great video of this perfect moment of u dancing on the tables hahaha.<br />I miss you guys en tabarouette, hopefully we can recreate a moment like this soon (en France hopefully, I need to travel, partir d'icitte seigneur).<br />Lots of love, ptit shot de vodka pour te célébrer, aweille un tit deuxième pour toi aussi.<br />bisousssss";
                audio.setAttribute("src", "../mus/tim.mp3");
                break;
            case "rudy":
                console.log("Message de Rudy");
                pageTitle.innerHTML = "Rudy";
                photoBack.setAttribute("src", "../img/rudy2.jpg");
                photoBack.setAttribute("alt", "Rudy avec un filtre pantin de cirque");
                photoFront.setAttribute("src", "../img/rudy.jpg");
                photoFront.setAttribute("alt", "Rudy dans une forêt enneigée");
                messageAuthor.innerHTML = "Rudy";
                message.innerHTML = "Bwananiversaiiiiire Maruuuu!<br />J’espère que tu vas bien, que ta nouvelle vie nantaise te plaît. Ton rire manque à Montréal!! Hâte de passer vous voir une fois ce Covid derrière nous!<br />A bientôt et très bonne fête à toi !!!!";
                audio.setAttribute("src", "../mus/rudy.mp3");
                break;
            case "catherine":
                console.log("Message de Catherine");
                pageTitle.innerHTML = "Maman";
                photoBack.setAttribute("src", "../img/catherine2.jpg");
                photoBack.setAttribute("alt", "Marussia et sa mère en vacances");
                photoFront.setAttribute("src", "../img/catherine.jpg");
                photoFront.setAttribute("alt", "Marussia et sa mère complices");
                messageAuthor.innerHTML = "Maman";
                message.classList.add("card__message__txt--less-margin");
                message.innerHTML = "Mon enfant, mon ange, ma beauté, ma fierté... je pense à toi et avec tout mon amour tous les jours depuis 26 ans, tu es ma grande, mon premier bébé, je t’aime si fort comme tu n’en as pas idée... mon « petit mini me » avec tes 15 cm au dessus de moi !! (mais comment as-tu fait cela ?!)<br />Je te souhaite mon ange un merveilleux anniversaire rempli de bonheur, de rires et de tendresse... Kocham cie ♥️<br />Ta petite mamounette";
                audio.setAttribute("src", "../mus/catherine.mp3");
                break;
            case "lila":
                console.log("Message de Lila-May");
                pageTitle.innerHTML = "Lila-May";
                photoBack.setAttribute("src", "../img/lila2.jpg");
                photoBack.setAttribute("alt", "Marussia joue avec Lila bébé");
                photoFront.setAttribute("src", "../img/lila.jpg");
                photoFront.setAttribute("alt", "Marussia et ses soeurs Lila et Juliette");
                messageAuthor.innerHTML = "Lila-May";
                message.innerHTML = "Ma Ma..ssia à moi, tu es ma grande sœur adorée... tu t’es blottie contre moi lorsque j’étais bébé, je m’en souviens encore... tu es ma grande sœur adorée... je t’aime fort pour l’éternité !! ♥️<br />Joyeux anniversaire ma grande poupée 🥰";
                audio.setAttribute("src", "../mus/lila.mp3");
                break;
            case "daphne":
                console.log("Message de Daphné");
                pageTitle.innerHTML = "Daphné";
                photoBack.setAttribute("src", "../img/daphne2.jpg");
                photoBack.setAttribute("alt", "Marussia porte Daphné comme dans le roi lion");
                photoFront.setAttribute("src", "../img/daphne.jpg");
                photoFront.setAttribute("alt", "Marussia fait jouer du ukulélé à Daphné");
                messageAuthor.innerHTML = "Daphné";
                message.innerHTML = "Tu as traumatisé ma vie de petit chien .. entre piscine tsunami, rallye de vélo et cours de philo cachée dans ton sac... j’en ai vécu des choses à tes côtés !! Mais je crois que j’ai aimé ça !! Un peu grâce à toi que mon petit cœur a voltigé... tu sais quoi... je t’aime waaaaf waaaf ♥️";
                audio.setAttribute("src", "../mus/daphne.mp3");
                break;
            case "tan":
                console.log("Message de Antoine et Coralie");
                pageTitle.innerHTML = "Antoine et Coralie";
                photoBack.setAttribute("src", "../img/tan2.jpg");
                photoBack.setAttribute("alt", "Antoine et Coralie avec leurs masques");
                photoFront.setAttribute("src", "../img/tan.jpg");
                photoFront.setAttribute("alt", "Antoine et Coralie en sortie bateau");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Antoine et Coralie";
                message.innerHTML = "Coucou Marussia,<br />Alors déjà: Joyeuuuux anniversaire!!!<br />Nous sommes super contents de votre retour et de pouvoir être avec vous à Nantes. Alors même si nous ne sommes pas là ce week end on fête ça très vite et passe un anniversaire du feu de dieu!<br />Pleiiiins de bisous, poutous !!";
                audio.setAttribute("src", "../mus/tan.mp3");
                break;
            case "alex":
                console.log("Message de Alex");
                pageTitle.innerHTML = "Alex";
                photoBack.setAttribute("src", "../img/alex2.jpg");
                photoBack.setAttribute("alt", "Alex devant une photo du postérieur de Marussia");
                photoFront.setAttribute("src", "../img/alex.jpg");
                photoFront.setAttribute("alt", "Alex, Marussia et Guillaume en soirée");
                messageAuthor.innerHTML = "Alex";
                message.innerHTML = "<i class='fas fa-guitar'></i><i class='fas fa-music'></i> Joyeux anniversaire Marussia<br />Tu es une fille géniale<br />Tu me manques beaucoup<br />Reviens à Montréaaal! <i class='fas fa-music'></i> <i class='fas fa-guitar'></i><br /><br />Joyeux anniversaire, je t'aime fort!!";
                audio.setAttribute("src", "../mus/alex.mp3");
                break;
            case "bulle":
                console.log("Message de Bulle et Sam");
                pageTitle.innerHTML = "Bulle et Sam";
                photoBack.setAttribute("src", "../img/bulle2.jpg");
                photoBack.setAttribute("alt", "Josie au soleil sur le canapé");
                photoFront.setAttribute("src", "../img/bulle.jpg");
                photoFront.setAttribute("alt", "Josie assise");
                messageAuthor.classList.add("card__message__author--long");
                messageAuthor.innerHTML = "Bulle et Sam";
                message.innerHTML = "La plus belle des fleurs te souhaite un magnifique anniversaire. Bon là elle est encore grassouillette mais promis elle fait des efforts. Tu es sa voisine préférée et on est bien d'accord !<br />Plein de belles soirées clandestines à venir pour la team Belzunce ❤";
                audio.setAttribute("src", "../mus/bulle.mp3");
                break;
        } 
    };
};

buildMessagePage();